#!/bin/bash

set -euo pipefail
set -x
rand_port() {
    #port=$(shuf -i 1025-40000 -n1)
    #seq 2025 40000|sort -R|head -n1
    #n different from port
    local n=$((RANDOM+7233))
    #initialize port unless unbound variable thrown
    port=$((RANDOM+7233))
    while :; do
    if [[ $n =~ 4 ]]; then
        local n=$((RANDOM+7233))
    else
        port=$n
    fi
    if [[ ! $port =~ 4 ]]; then
        printf "%d" $port
        break
    fi
    done
}

set_port() {
#Enable timeout for read
#need to use if statement; read -t10 -p "Please set up a server port(Default: 18388): " SERVER_PORT
#Validity checkup
default=$(rand_port)
read -p "Please enter server port(Default: ${default})..." SERVER_PORT
while [[ ! ( ${SERVER_PORT:=${default}} =~ ^[[:digit:]]{4,5}$ && $SERVER_PORT -gt 1024 && $SERVER_PORT -lt 65535 ) ]]; do
  echo -n "Please enter port number between 1024 and 65535: "
  read SERVER_PORT
done

#Set the default SERVER_PORT for furhter use
printf "%s${RED}%s${NC}\n" "You have selected server port: " "${SERVER_PORT}."
}
